### ISSUE TITLE
Shadow baking

### ISSUE THREAD

**Issue by lm165678** [ands/lightmapper#14]
Hello, I am studying your code, I tried to modify the shader to add bakeScene, but it seems that the shadow cannot be baked properly. Can you tell me an idea? Or provide some reference code? Sorry, I am a novice. Thank you!

**Comment by ands** [comment]
Hey @lm165678!
You can find reference code in the [example.c](https://github.com/ands/lightmapper/blob/master/example/example.c) file.
From your description it is not clear which part is not working. Can you provide more information please (e.g. screenshots)?
What are you trying to achieve and what does your setup look like? Would you mind sharing your code maybe?

**Comment by lm165678** [comment]
Sorry to reply you so late, I think I may know the reason. Radiosity does not seem to be used to bake shadows, but to simulate global illumination. Therefore, I used direct ray tracing to mark shadows and illuminate the part, and then used radiosity to bounce multiple times to simulate global illumination.

**Comment by ands** [comment]
You could use this library to bake shadows from area light sources (see example images on the front page). But since you seem to have a solution now, I'll close this ticket then :).
