### ISSUE TITLE
License

### ISSUE THREAD

**Issue by codingus-g** [ands/lightmapper#15]
You should probably add a license to this repo, for legal reasons.

**Comment by Qix-** [comment]
```c
* License:                                                 *
* This software is in the public domain.                   *
* Where that dedication is not recognized,                 *
* you are granted a perpetual, irrevocable license to copy *
* and modify this file however you want.                   *
```

**Comment by ands** [comment]
Thanks @Qix- :)
@baboongd: Since this is a single header file library, the license is kept in the header of the lib to avoid having to move/copy around more than that one file.

**Comment by codingus-g** [comment]
Great sorry, im used to it being displayed on the right of the github page.
