### ISSUE TITLE
readme.md: uvatlas is now on Github

### ISSUE THREAD

**Issue by Kristine1975** [ands/lightmapper#19]
The link to "uvatlas" doesn't work anymore because codeplex no longer exists: https://github.com/ands/lightmapper/blob/eeaad30be20158d6164d0becceda8d7d742adc1f/README.md?plain=1#L14

uvatlas is now on github: https://github.com/microsoft/UVAtlas

**Comment by ands** [comment]
Thank you @Kristine1975. I've updated the link destination and also added a link to xatlas (https://github.com/jpcy/xatlas). :)
