### ISSUE TITLE
Proper obj format

### ISSUE THREAD

**Issue by rasteron** [ands/lightmapper#6]
Hi, I'm trying to test other objs or just simply open the current example `gazebo.obj` model to Blender or any other modelling tool and exporting it again. The new output model crashes the example program with this error.

```
File: C:\ands\example\example.c, Line 319
Expression: !"unknown identifier"
```

Any ideas?

**Comment by JDragan** [comment]
I have the same problem.
Im exporting from Blender, and whenever I want to generate custom UV Lightmap,
the result is mess.
@rasteron make sure you triangulate your mesh (Ctrl+T), import the example, then experiment with the settings.
![result](https://cloud.githubusercontent.com/assets/9966157/25159929/3ccd4be4-24b3-11e7-85fd-b5e07d85d394.jpg)

**Comment by rasteron** [comment]
@r3aktormk Thanks! but still no luck and same error even exporting with triangulate mesh..

**Comment by ands** [comment]
Sorry, I should have mentioned that the master branch only has the minimum viable obj parser to read that one obj file. If you switch to the development branch, you'll get a proper obj loader and slightly better lightmapping performance. :)

**Comment by rasteron** [comment]
Awesome, thanks works great now! :D

**Comment by ands** [comment]
Cool :)
